ci: drop Node.js 10
fastify/workflows pull request #15
Opened 2022-02-25 08:19 UTC by darkgl0w

Hello.

This PR aims to :
- drop Node.js version 10 whose support has ended since 04/30/2021

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-02-25 08:27 UTC, mcollina commented
Doing this is a semver-major change for all modules.

2022-02-25 08:37 UTC, Fdawgs commented
I think it's best to hold fire on this until Fastify v4, and then drop node 10 and 12 at the same time. 😁

2022-02-25 08:51 UTC, darkgl0w commented
I will update the PR to drop Node 12 at the same time and mark this as draft until v4 is released :d

2022-02-25 22:24 UTC, mcollina commented
Could the workflows have a version number?

2022-02-26 04:45 UTC, climba03003 commented
> Could the workflows have a version number?

Yes, and it need to manage multiple tag. e.g. `3.0.0` needs `v3`, `v3.0` and `v3.0.0` tags.

2022-02-26 07:40 UTC, mcollina commented
I would recommend to land this a semver-major thenz

2022-02-28 09:10 UTC, Fdawgs commented
I'm hesitant to land this until Fastify v4 because dependabot will automatically bump all repos currently using this workflow from v2 to the new v3, thus dropping all testing for node 10 and 12 before we officially move away in v4.

2022-03-02 13:40 UTC, mcollina commented
Ok, let's do this as part of the release choreograpy. Could you add it to the issue?

2022-03-04 07:29 UTC, climba03003 requested changes
I think `node@18` will release (2022-04-19) faster than `fastify@4` release cycle. I drop a Request Changes here for reminder.

2022-03-05 15:35 UTC, darkgl0w commented
> I think `node@18` will release (2022-04-19) faster than `fastify@4` release cycle. I drop a Request Changes here for reminder.

I will add 18 to the matrix when they cut the 18th branch.
Usually a major branch is cut before the LTS release.

(would be good if GitHub had a reminder feature :d)

2022-05-05 08:38 UTC, Fdawgs commented
As v4 is now being moved on in the modules themselves (https://github.com/fastify/fastify-compress/pull/224), maybe now is a good time to land this?

2022-05-05 13:12 UTC, mcollina commented
We really need a way to have multiple version of our workflow.

2022-05-05 17:08 UTC, merged